"""Git + GitHub operations: apply fixes on a new branch and open a PR."""

from __future__ import annotations

import os
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

from git import Repo
from github import Github, GithubException

from .models import FileFix, Finding, ScanResult


@dataclass
class PRResult:
    branch: str
    url: Optional[str] = None
    number: Optional[int] = None
    pushed: bool = False
    committed: bool = False
    message: str = ""


def _default_branch_name() -> str:
    return f"secagent/auto-remediation-{time.strftime('%Y%m%d-%H%M%S')}"


def detect_remote_slug(repo: Repo) -> Optional[str]:
    """Return 'owner/name' parsed from the origin remote URL, if GitHub."""
    try:
        url = repo.remotes.origin.url
    except (AttributeError, ValueError):
        return None
    match = re.search(r"github\.com[:/]([^/]+/[^/]+?)(?:\.git)?$", url)
    return match.group(1) if match else None


class GitRemediationRunner:
    def __init__(self, root: str, github_token: str = None):
        self.root = str(Path(root).resolve())
        self.repo = Repo(self.root)
        # Use environment variable for GitHub token
        self.github_token = github_token or os.getenv('GITHUB_TOKEN')

    def apply_fixes(self, fixes: List[FileFix]) -> List[str]:
        """Write patched contents to disk. Returns the list of changed paths."""
        changed: List[str] = []
        for fix in fixes:
            target = Path(self.root) / fix.file
            target.parent.mkdir(parents=True, exist_ok=True)
            content = fix.new_content
            if not content.endswith("\n"):
                content += "\n"
            target.write_text(content, encoding="utf-8")
            changed.append(fix.file)
        return changed

    def commit_on_branch(
        self,
        changed_files: List[str],
        branch: str,
        commit_message: str,
    ) -> bool:
        """Create `branch` from current HEAD, stage files, and commit."""
        if not changed_files:
            return False
        new_branch = self.repo.create_head(branch)
        new_branch.checkout()
        self.repo.index.add(changed_files)
        author = os.getenv("SECAGENT_GIT_AUTHOR", "secagent <secagent@users.noreply.github.com>")
        self.repo.index.commit(commit_message, author=None, committer=None)
        return True

    def push_branch(self, branch: str) -> None:
        origin = self.repo.remotes.origin
        # Use credential helper instead of embedding token in URL
        try:
            origin.push(refspec=f"{branch}:{branch}")
        except Exception as e:
            print(f"Failed to push branch {branch}: {e}")

    def open_pull_request(
        self,
        slug: str,
        branch: str,
        base: str,
        title: str,
        body: str,
    ) -> tuple[str, int]:
        gh = Github(self.github_token)
        gh_repo = gh.get_repo(slug)
        pr = gh_repo.create_pull(title=title, body=body, head=branch, base=base)
        return pr.html_url, pr.number

    def current_branch(self) -> str:
        try:
            return self.repo.active_branch.name
        except TypeError:
            return "HEAD"


def build_pr_body(scan: ScanResult, fixes: List[FileFix], min_sev: str) -> str:
    counts = scan.counts()
    lines = [
        "## Automated security remediation",
        "",
        "This PR was generated by **secagent**, which scanned the repository with an "
        "OpenAI model, identified security issues, and applied fixes.",
        "",
        f"**Findings:** {counts['critical']} critical · {counts['high']} high · "
        f"{counts['medium']} medium · {counts['low']} low",
        f"**Auto-remediated at severity ≥ `{min_sev}`:** {len(fixes)} file(s)",
        "",
        "### Fixes applied",
    ]
    for fix in fixes:
        lines.append(f"\n#### `{fix.file}`")
        if fix.addressed_findings:
            for title in fix.addressed_findings:
                lines.append(f"- {title}")
        if fix.explanation:
            lines.append(f"\n{fix.explanation}")

    remaining = [
        f for f in scan.findings
        if f.file not in {fx.file for fx in fixes}
    ]
    if remaining:
        lines.append("\n### Findings not auto-fixed (review manually)")
        for f in remaining:
            lines.append(f"- **{f.severity.value}** `{f.location()}` — {f.title}")

    lines.append(
        "\n---\n> ⚠️ Auto-generated fixes. Review the diff and run your test suite "
        "before merging."
    )
    return "\n".join(lines)


def build_commit_message(fixes: List[FileFix]) -> str:
    n = len(fixes)
    subject = f"fix(security): auto-remediate {n} file(s) flagged by secagent"
    files = "\n".join(f"- {fx.file}" for fx in fixes)
    return f"{subject}\n\nRemediated files:\n{files}\n"
